In [1]:
import numpy as np
x= np.array([1,2,3]) #numpy single dimensional array 
print (x)

[1 2 3]


In [42]:
x= np.array([(2,3,32,4),(61,1,9,-5),(3,6,7,10)])    # multidimensional array using numpy
print(x)

[[ 2  3 32  4]
 [61  1  9 -5]
 [ 3  6  7 10]]


In [ ]:
# program to compare the size acquired by a list and numpy array
#array acquires less memory  than list, faster and convenient
import numpy as np
import sys          #system module--gives system parameters info

list1= range(100)#  sys.getsize of() ---Return the size of an object in bytes."sys is giving memory location (system info)
print("memory size acquired by list1 is ",sys.getsizeof(4)*len(list1))  #size of list=get size of one element and multiply by length of list 

array1= np.arange(100)        #here array range is defined as arange()
print("memory size acquired by array1 is ", array1.size *array1.itemsize)  #space occupied by numpy array *length of array(.itemsize)

In [9]:
print(x.shape)  #shape of matrix (r,c)

(3, 4)


In [43]:
print(x.reshape(4,3)) #interchange rows and columns

[[ 2  3 32]
 [ 4 61  1]
 [ 9 -5  3]
 [ 6  7 10]]


In [33]:
print(x[1,2])  # printing 1st element of row 2  as indexing starts from 0

9


In [86]:
print(x[1:2,2])   

[9]


In [108]:
print("squarerrot is:\n",np.sqrt(x))

squarerrot is:
 [[1.41421356 1.73205081 5.65685425 2.        ]
 [7.81024968 1.         3.                nan]
 [1.73205081 2.44948974 2.64575131 3.16227766]]


c:\users\r\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [106]:
deviation= np.std(x)
print("standard deviation is: ",deviation)

standard deviation is:  17.322713092610204


In [103]:
a1= np.array([(2,3,4),(5,6,7),(8,9,10)])
a2= np.array([(11,12,13),(14,15,16),(17,18,19)])
print("addition of two matrix is:\n",a1+a2)  #all mathematic operatons can beperformed like addition

addition of two matrix is:
 [[13 15 17]
 [19 21 23]
 [25 27 29]]


In [113]:
print("vertical stacking:\n",np.vstack((a1,a2)))  # vertical stackig means two array are concatenated vertically

vertical stacking:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [114]:
print("horizontal stacking is\n",np.hstack((a1,a2)))

horizontal stacking is
 [[ 2  3  4 11 12 13]
 [ 5  6  7 14 15 16]
 [ 8  9 10 17 18 19]]


In [120]:
print(a2.ravel())

[11 12 13 14 15 16 17 18 19]
