In [2]:
#### import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import os

#Open a Zip File
from zipfile import ZipFile


#Image manipulation
from PIL import Image
print('imported')

imported


In [3]:
train_zip= ZipFile("../data/train.zip",mode='r')

In [5]:
labels= pd.read_csv("../data/labels.csv")
labels.shape

(10222, 2)

In [10]:
unique_breeds= labels["breed"].unique()
len(unique_breeds)

120

In [191]:
total_breeds_taken= labels.groupby("breed").count().reset_index().sort_values(by="id",ascending= False).head(15)
len(total_breeds_taken)
total_breeds_taken.head(5)

breed   id
97    scottish_deerhound  126
73           maltese_dog  117
1           afghan_hound  116
42           entlebucher  115
11  bernese_mountain_dog  114

In [192]:
total_breeds_taken.shape

(15, 2)

In [193]:
unique_breeds= list(total_breeds_taken["breed"])
unique_breeds

['scottish_deerhound',
 'maltese_dog',
 'afghan_hound',
 'entlebucher',
 'bernese_mountain_dog',
 'shih-tzu',
 'great_pyrenees',
 'pomeranian',
 'basenji',
 'samoyed',
 'airedale',
 'tibetan_terrier',
 'leonberg',
 'cairn',
 'beagle']

In [194]:
gross_breeds= labels[labels["breed"].isin(unique_breeds)]
print(len(gross_breeds))  
gross_breeds.shape

1672


(1672, 2)

In [236]:
def one_hot_encoder(breed_list):
    one_hot= np.zeros([20,20])
    
    for i,each in enumerate(breed_list):
        inside_list=[]
        for j ,eachinside in enumerate(each):
            if i==j:
                inner_
            
            
        

In [237]:
my= one_hot_encoder(unique_breeds)
print(my)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.